-- MySQL Script generated by MySQL Workbench
-- vie 14 sep 2018 08:26:00 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria_evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria_evento` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `cat_evento` VARCHAR(50) NULL,
  `icono` VARCHAR(15) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invitados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`invitados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`invitados` (
  `idInvitado` INT NOT NULL AUTO_INCREMENT,
  `nombre_invitado` VARCHAR(45) NULL,
  `apellido_invitado` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `url_imagen` VARCHAR(50) NULL,
  PRIMARY KEY (`idInvitado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nombre_evento` VARCHAR(60) NULL,
  `dia_evento` VARCHAR(45) NULL,
  `hora_evento` TIME NULL,
  `clave` VARCHAR(10) NULL,
  `idCategoria` INT NOT NULL,
  `idInvitado` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_eventos_categoria_evento_idx` (`idCategoria` ASC),
  INDEX `fk_eventos_invitados1_idx` (`idInvitado` ASC),
  CONSTRAINT `fk_eventos_categoria_evento`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`categoria_evento` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_invitados1`
    FOREIGN KEY (`idInvitado`)
    REFERENCES `mydb`.`invitados` (`idInvitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`publico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`publico` (
  `idPublico` INT NOT NULL,
  `nombre_persona` VARCHAR(45) NOT NULL,
  `apellido_persona` VARCHAR(45) NOT NULL,
  `cant_pases_un_dia` INT NULL,
  `cant_pases_dos_dias` INT NULL,
  `cant_pases_tres_dias` INT NULL,
  `cant_camisas` INT NULL,
  `cant_etiquetas` INT NULL,
  `regalo` VARCHAR(45) NOT NULL,
  `monto_total` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPublico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos_has_publico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventos_has_publico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventos_has_publico` (
  `idEvento` INT NOT NULL,
  `idPublico` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idPublico`),
  INDEX `fk_eventos_has_publico_publico1_idx` (`idPublico` ASC),
  INDEX `fk_eventos_has_publico_eventos1_idx` (`idEvento` ASC),
  CONSTRAINT `fk_eventos_has_publico_eventos1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `mydb`.`eventos` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_publico_publico1`
    FOREIGN KEY (`idPublico`)
    REFERENCES `mydb`.`publico` (`idPublico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
